### ISSUE TITLE
Question: Where are yarn workspaces?

### ISSUE THREAD

**Issue by gabrielliwerant** [DmacMcgreg/Component-Library-Monorepo-Template-RollupJS-Lerna-Yarn-Workspaces#2]
Hello, I appreciate the effort in making this repo, as I am attempting to solve a similar problem and am looking at a similar set of technologies.

The project indicates in the README that it is using yarn workspaces, however I do not see this implemented anywhere (I am expecting `"workspaces"` in one of the `package.json` files somewhere). Was this an oversight, or am I missing something?

Thank you.

**Comment by DmacMcgreg** [comment]
Good question,
It's been so long now since I've used it, but I remember running into some
issues with yarn workspaces at the time.
You should be able to do exactly that in the package.json, and it might
work locally.
I think there are other solutions out there for doing this type of
behaviour now, but I'm kind of out of the developer scene at the moment so
I can't really tell you.
If you add it to your package.json, it should work...

Take care

**Comment by DmacMcgreg** [comment]
For anyone viewing this now, i recommend using pnpm workspaces
https://pnpm.io/workspaces
